
# API Credentials
AAM_API_ACCESS_TOKEN = 'PLACE-YOUR-ACCESS-TOKEN-HERE'

# API Paths
AAM_BASE_API_PATH = 'https://api-sandbox.demdex.com'
AAM_OAUTH_TOKEN_API_PATH = AAM_BASE_API_PATH + '/oauth/token'
AAM_SELF_USER_API_PATH = AAM_BASE_API_PATH + '/v1/users/self'
AAM_DATASOURCE_API_PATH = AAM_BASE_API_PATH + '/v1/datasources'
AAM_TRAIT_API_PATH = AAM_BASE_API_PATH + '/v1/traits'
AAM_TRAIT_FOLDER_API_PATH = AAM_BASE_API_PATH + '/v1/folders/traits'
AAM_SEGMENT_API_PATH = AAM_BASE_API_PATH + '/v1/segments'
AAM_SEGMENT_FOLDER_API_PATH = AAM_BASE_API_PATH + '/v1/folders/segments'
AAM_DESTINATION_API_PATH = AAM_BASE_API_PATH + '/v1/destinations'

# Data Elements
AAM_DESTINATION_ID = 'PLACE-DESTINATION-ID-HERE'
