
# API Credentials
AAM_API_ACCESS_TOKEN = 'ec764e79-3932-4444-82d3-43b463c133fc' # PLACE-YOUR-ACCESS-TOKEN-HERE


# API Paths
AAM_BASE_API_PATH = 'https://use-qe4-por1.demdex.com/portal/api'
AAM_OAUTH_TOKEN_API_PATH = AAM_BASE_API_PATH.replace('/api', '') + '/oauth/token'
AAM_SELF_USER_API_PATH = AAM_BASE_API_PATH + '/v1/users/self'
AAM_DATASOURCE_API_PATH = AAM_BASE_API_PATH + '/v1/datasources'
AAM_TRAIT_API_PATH = AAM_BASE_API_PATH + '/v1/traits'
AAM_TRAIT_FOLDER_API_PATH = AAM_BASE_API_PATH + '/v1/folders/traits'
AAM_SEGMENT_API_PATH = AAM_BASE_API_PATH + '/v1/segments'
AAM_SEGMENT_FOLDER_API_PATH = AAM_BASE_API_PATH + '/v1/folders/segments'
AAM_DESTINATION_API_PATH = AAM_BASE_API_PATH + '/v1/destinations'


AAM_DESTINATION_ID = '43353'
